import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const COLOR_MAP: Record<string, { bg: string; label: string; hex: string }> = {
  blue:   { bg: "bg-blue-500",   label: "Bleu",   hex: "#3B82F6" },
  pink:   { bg: "bg-pink-400",   label: "Rose",   hex: "#F472B6" },
  yellow: { bg: "bg-yellow-400", label: "Jaune",  hex: "#FBBF24" },
  white:  { bg: "bg-gray-100",   label: "Blanc",  hex: "#F3F4F6" },
  green:  { bg: "bg-emerald-500",label: "Vert",   hex: "#10B981" },
  orange: { bg: "bg-orange-400", label: "Orange", hex: "#FB923C" },
  purple: { bg: "bg-violet-500", label: "Violet", hex: "#8B5CF6" },
  black:  { bg: "bg-gray-900",   label: "Noir",   hex: "#111827" },
};

export const DEMO_PRODUCTS = [
  {
    id: "1",
    name: "Saphir de Ceylan",
    description: "Magnifique saphir bleu cornflower d'origine Sri Lanka, non chauffé. Couleur vive et exceptionnelle.",
    color: "blue" as const,
    weight_ct: 4.32,
    origin: "Sri Lanka",
    clarity: "VVS",
    cut: "Ovale",
    certificate: "GRS",
    images: [],
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Saphir Rose Padparadscha",
    description: "Saphir padparadscha aux teintes orangé-rose caractéristiques. Pièce rarissime.",
    color: "orange" as const,
    weight_ct: 2.15,
    origin: "Madagascar",
    clarity: "VS",
    cut: "Coussin",
    certificate: "GIA",
    images: [],
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Saphir Rose de Madagascar",
    description: "Saphir rose intense, taille brillant. Couleur naturelle non traitée.",
    color: "pink" as const,
    weight_ct: 3.08,
    origin: "Madagascar",
    clarity: "VS",
    cut: "Brillant",
    certificate: "Gübelin",
    images: [],
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Saphir Jaune de Ceylan",
    description: "Saphir jaune lumineux, couleur miel dorée naturelle.",
    color: "yellow" as const,
    weight_ct: 5.60,
    origin: "Sri Lanka",
    clarity: "VVS",
    cut: "Ovale",
    certificate: "GRS",
    images: [],
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Saphir Blanc Star",
    description: "Saphir étoilé blanc naturel, astérisme à 6 branches parfaitement défini.",
    color: "white" as const,
    weight_ct: 7.80,
    origin: "Birmanie",
    clarity: "Star",
    cut: "Cabochon",
    images: [],
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Saphir Vert Australien",
    description: "Saphir vert profond aux reflets teal caractéristiques de l'Australie.",
    color: "green" as const,
    weight_ct: 3.45,
    origin: "Australie",
    clarity: "VS",
    cut: "Poire",
    images: [],
    is_available: true,
    created_at: new Date().toISOString(),
  },
];
